---
title: "Lab 03 - Nobel laureates"
author: "Barbara Mu"
date: "01/23/2026"
output: github_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

```{r load-data, message=FALSE}
nobel <- read_csv("data/nobel.csv")
```

## Exercises

### Exercise 1
```{r data observation}
head(nobel)
```
```{r}
summary(nobel)
```


### Exercise 2
```{r data filtering}
nobel_living <- nobel %>% 
  filter(is.na(died_date)) %>% 
  filter(!is.na(country)) %>% 
  filter(gender != "org")
  
```


```{r}
nobel_living <- nobel_living %>%
  mutate(
    country_us = if_else(country == "USA", "USA", "Other")
  )
```

```{r}
nobel_living_science <- nobel_living %>%
  filter(category %in% c("Physics", "Medicine", "Chemistry", "Economics"))
```

### Exercise 3
```{r Visualization}
ggplot(data = nobel_living_science, aes(x = country_us)) + 
  geom_boxplot() + 
  facet_wrap(~category) + 
  coord_flip()
```



### Exercise 4
```{r}

```

...

### Exercise 5

...

### Exercise 6

...
